# Generated by Django 5.1.7 on 2025-03-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_alter_policy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='policies/images/'),
        ),
    ]
