# Generated by Django 5.1.7 on 2025-03-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(upload_to='policies/files/'),
        ),
    ]
