# Generated by Django 5.1.7 on 2025-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_alter_policy_category_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Engineering', 'Engineering'), ('Private', 'Private Sectors'), ('Information Security', 'Information Security'), ('Governance & Quality ', 'Governance & Quality '), ('Communication', 'Communication')], max_length=50),
        ),
    ]
